# Generated by Django 4.0.1 on 2022-02-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('gender', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
