# Generated by Django 4.0.1 on 2022-02-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
