# Generated by Django 4.0.1 on 2022-01-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(default='nais', max_length=150),
            preserve_default=False,
        ),
    ]
