# Generated by Django 4.0.1 on 2022-01-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.CharField(max_length=150),
        ),
    ]
